# Generated by Django 3.2.4 on 2021-06-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240)),
                ('center', models.CharField(max_length=100)),
                ('eventType', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=10000)),
                ('location', models.CharField(max_length=240)),
                ('beginingDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
    ]
