# Generated by Django 3.2.4 on 2021-08-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReport', '0005_auto_20210809_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreport',
            name='beginingDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='endDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
