# Generated by Django 3.2 on 2022-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReport', '0007_auto_20210809_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='strenghts',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventreport',
            name='weaknesses',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
