# Generated by Django 3.2 on 2022-05-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventReport', '0008_auto_20220526_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreport',
            old_name='strenghts',
            new_name='strengths',
        ),
    ]
