# Generated by Django 3.2 on 2022-06-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReport', '0009_rename_strenghts_eventreport_strengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='goals',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
