# Generated by Django 3.2.3 on 2021-06-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('areas', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
                ('participants', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('goals', models.CharField(max_length=40)),
                ('strengths', models.CharField(max_length=40)),
                ('weaknesses', models.CharField(max_length=40)),
                ('improvements', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
            ],
        ),
    ]
