# Generated by Django 3.2.3 on 2021-06-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.CharField(max_length=40),
        ),
    ]
