# Generated by Django 3.2.3 on 2021-06-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='areas',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='branch',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='goals',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='improvements',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='participants',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='strengths',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='report',
            name='weaknesses',
            field=models.CharField(default='', max_length=40),
        ),
    ]
