# Generated by Django 3.2.3 on 2021-06-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210602_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='areas',
            field=models.CharField(default=' ', max_length=140),
        ),
    ]
