# Generated by Django 3.2.4 on 2021-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='improvements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='strengths',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='weaknesses',
            field=models.TextField(),
        ),
    ]
