# Generated by Django 3.2.4 on 2021-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_report_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='areas',
            field=models.CharField(default=' ', max_length=240),
        ),
        migrations.AlterField(
            model_name='report',
            name='branch',
            field=models.CharField(default=' ', max_length=240),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.CharField(default=' ', max_length=240),
        ),
        migrations.AlterField(
            model_name='report',
            name='goals',
            field=models.TextField(default=' ', max_length=240),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(default=' ', max_length=240),
        ),
        migrations.AlterField(
            model_name='report',
            name='materials',
            field=models.CharField(default=' ', max_length=240),
        ),
        migrations.AlterField(
            model_name='report',
            name='participants',
            field=models.CharField(default=' ', max_length=240),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default=' ', max_length=240),
        ),
        migrations.AlterField(
            model_name='report',
            name='username',
            field=models.CharField(default=' ', max_length=240),
        ),
    ]
