# Generated by Django 3.2.4 on 2021-06-09 15:04

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0009_auto_20210609_1357'),
    ]

    operations = [
        UnaccentExtension()
    ]
