# Generated by Django 3.2.4 on 2021-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=' ', max_length=240)),
                ('branch', models.CharField(default=' ', max_length=240)),
                ('areas', models.CharField(default=' ', max_length=240)),
                ('title', models.CharField(default=' ', max_length=240)),
                ('location', models.CharField(default=' ', max_length=240)),
                ('date', models.DateField()),
                ('duration', models.CharField(default=' ', max_length=240)),
                ('participants', models.CharField(default=' ', max_length=240)),
                ('materials', models.CharField(default=' ', max_length=240)),
                ('goals', models.TextField(default=' ', max_length=240)),
                ('description', models.CharField(max_length=5000)),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('improvements', models.TextField()),
            ],
        ),
    ]
