# Generated by Django 3.2.4 on 2021-06-16 12:22

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('activityReport', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
