# Generated by Django 3.2.4 on 2021-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityReport', '0005_alter_activityreport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
