# Generated by Django 3.2.4 on 2021-06-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityReport', '0006_alter_activityreport_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreport',
            name='photo',
        ),
    ]
