# Generated by Django 3.2.4 on 2021-07-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityReport', '0007_remove_activityreport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='goals',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='materials',
            field=models.TextField(),
        ),
    ]
