# Generated by Django 3.2.4 on 2021-08-02 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityReport', '0008_auto_20210705_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
