# Generated by Django 3.2.4 on 2021-08-27 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityReport', '0009_alter_activityreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
