# Generated by Django 3.2.4 on 2021-08-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210615_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activityReports',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eventReports',
        ),
    ]
